#version de docker-compose
version: '3'
#Lista de servicios
services:
 flask_app: #servicios app
   build:   #lista de params.
     context: .
     dockerfile: Dockerfile
   ports:
     - "5005:5005" # puerto que expone el contenedor : puerto del host donde escuchamos.
   # restart: always # En caso de error, reintenta.
   volumes:
     - .:/app
   env_file:
     - .env
   depends_on:
     - mysql_db
   container_name: flask_app_a

 mysql_db:
   image: mysql:5.7  # Use the official MySQL 5.7 image from Docker Hub
   environment:
     MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
     MYSQL_DATABASE: sql_alchemy_a  # Create a database named 'mydatabase'
     MYSQL_USER: db_user  # Create a MySQL user 'myuser'
     MYSQL_PASSWORD: root  # Set the password for 'myuser'
   volumes:
     - ./.data/db:/var/lib/mysql
   ports:
     - "3307:3306"  # Map host port 3307 to container port 3306 for MySQL
   restart: always  # Restarts the MySQL container if it stops or crashes
   container_name: mysql_database