"""se agrego la edicion en caracteristicas

Revision ID: 54c8aa13410c
Revises: e90f62b6c343
Create Date: 2024-08-09 14:28:29.988389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54c8aa13410c'
down_revision = 'e90f62b6c343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('pais', schema=None) as batch_op:
        batch_op.drop_index('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pais', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
