"""Primera migracion

Revision ID: 66349b698333
Revises: 782ac1d58c6c
Create Date: 2024-07-23 10:04:32.105799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66349b698333'
down_revision = '782ac1d58c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint('modelo_ibfk_1', type_='foreignkey')
        batch_op.drop_column('caracteristica_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caracteristica_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('modelo_ibfk_1', 'caracteristica', ['caracteristica_id'], ['id'])

    # ### end Alembic commands ###
