"""Primera migracion

Revision ID: 782ac1d58c6c
Revises: 688cb39ac613
Create Date: 2024-07-23 10:03:53.773441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782ac1d58c6c'
down_revision = '688cb39ac613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caracteristica_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caracteristica_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['caracteristica.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caracteristica_modelo')
    # ### end Alembic commands ###
