"""Primera migracion

Revision ID: 8fd5d358b547
Revises: 66349b698333
Create Date: 2024-07-23 10:16:30.637030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fd5d358b547'
down_revision = '66349b698333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona')
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('mail', sa.String(length=50), nullable=False))
        batch_op.drop_column('cantidad_disponible')
        batch_op.drop_column('ubicacion_almacen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_almacen', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('cantidad_disponible', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('mail')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.create_table('persona',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('mail', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
