"""empty message

Revision ID: a5766278f649
Revises: 5dfd9f640013
Create Date: 2024-08-10 23:38:24.328562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5766278f649'
down_revision = '5dfd9f640013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('cuit',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('cuit',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
